import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import App from "./App";

describe("Mercadinho Mini App flow", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
    window.history.pushState({}, "", "/");
  });

  it("points /painel to the official bot-mercearia control panel", () => {
    window.history.pushState({}, "", "/painel");

    render(<App />);

    expect(screen.getByRole("heading", { name: /painel oficial/i })).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /abrir painel oficial/i })).toHaveAttribute(
      "href",
      "http://127.0.0.1:8787/admin",
    );
    expect(screen.queryByRole("navigation", { name: /navegacao do painel/i })).not.toBeInTheDocument();
  });

  it("lets the customer switch sections from the right side menu", async () => {
    const user = userEvent.setup();

    render(<App />);

    expect(screen.queryByRole("region", { name: /carrossel de secoes/i })).not.toBeInTheDocument();

    await user.click(screen.getByRole("button", { name: /abrir menu de secoes/i }));
    expect(screen.getByRole("dialog", { name: /menu de secoes/i })).toBeInTheDocument();
    await user.click(screen.getByRole("button", { name: /abrir secao padaria/i }));

    expect(screen.getByText("Pao frances")).toBeInTheDocument();
    expect(screen.queryByText("Banana prata")).not.toBeInTheDocument();
    expect(screen.queryByRole("dialog", { name: /menu de secoes/i })).not.toBeInTheDocument();
  });

  it("loads the customer catalog generated by the official control panel", async () => {
    const fetchMock = vi.fn(async (input: RequestInfo | URL, _init?: RequestInit) => {
      const url = String(input);
      if (url.includes("/api/miniapp/catalogo")) {
        return Response.json({
          ok: true,
          catalogo: {
            produtos: [
              {
                id: "nutella-650g",
                nome: "Nutella Creme de Avela",
                secao_nome: "Mercearia",
                secao: "mercearia",
                unidade: "650g",
                preco: 65.99,
                imagem: "nutella.png",
                estoque: 7,
              },
            ],
          },
        });
      }
      return Response.json({ ok: true });
    });
    vi.stubGlobal("fetch", fetchMock);

    render(<App />);

    expect(await screen.findByText("Nutella Creme de Avela")).toBeInTheDocument();
    expect(fetchMock).toHaveBeenCalledWith("/api/miniapp/catalogo");
  });

  it("uses a visual fallback when a product image from the official panel cannot load", async () => {
    const user = userEvent.setup();
    const fetchMock = vi.fn(async () =>
      Response.json({
        ok: true,
        catalogo: {
          produtos: [
            {
              id: "ovos_1",
              nome: "Ovo Branco c/30 unidades",
              secao_nome: "Ovos",
              unidade: "un",
              preco: 20,
              estoque: 5,
              imagem: "https://assets.example.invalid/produto-bloqueado.jpg",
            },
          ],
        },
      }),
    );
    vi.stubGlobal("fetch", fetchMock);

    render(<App />);

    expect(await screen.findByText("Ovo Branco c/30 unidades")).toBeInTheDocument();
    fireEvent.error(screen.getByTestId("product-image-ovos_1"));
    expect(screen.getByTestId("product-image-fallback-ovos_1")).toBeInTheDocument();

    await user.click(screen.getByRole("button", { name: "Adicionar Ovo Branco c/30 unidades" }));
    await user.click(screen.getByRole("button", { name: "Abrir checkout" }));
    fireEvent.error(screen.getByTestId("checkout-product-image-ovos_1"));
    expect(screen.getByTestId("checkout-product-image-fallback-ovos_1")).toBeInTheDocument();
  });

  it("shows product carousels for each section on the homepage", () => {
    render(<App />);

    expect(screen.getByRole("region", { name: /produtos de hortifruti/i })).toBeInTheDocument();
    expect(screen.getByRole("region", { name: /produtos de padaria/i })).toBeInTheDocument();
    expect(screen.getByRole("region", { name: /produtos de bebidas/i })).toBeInTheDocument();
    expect(screen.getAllByText("Banana prata").length).toBeGreaterThan(0);
    expect(screen.getByText("Pao frances")).toBeInTheDocument();
    expect(screen.getByText("Leite integral")).toBeInTheDocument();
  });

  it("keeps the add button inside the product image area", () => {
    render(<App />);

    const addButton = screen.getByRole("button", { name: /adicionar banana prata/i });

    expect(addButton.closest(".product-media")).not.toBeNull();
  });

  it("keeps the Mini App to menu and checkout, then creates a real Pix order in bot-mercearia", async () => {
    const user = userEvent.setup();
    const fetchMock = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("/api/miniapp/checkout/create")) {
        return Response.json({
          ok: true,
          pedido: {
            id: "MJ-TESTE-1",
            status: "aguardando_comprovante",
            total: 4.99,
          },
          pix: {
            copiaCola: "000201PIXTESTE",
            recebedor: "Mercadinho M&J",
            valor: 4.99,
          },
        });
      }
      return Response.json({
        ok: true,
        catalogo: { produtos: [] },
      });
    });
    vi.stubGlobal("fetch", fetchMock);

    render(<App />);

    await user.click(screen.getByRole("button", { name: /adicionar banana prata/i }));
    expect(screen.getByRole("button", { name: /diminuir banana prata/i })).toBeInTheDocument();

    await user.click(screen.getByRole("button", { name: /diminuir banana prata/i }));
    expect(screen.getByRole("button", { name: /abrir checkout/i })).toBeDisabled();

    await user.click(screen.getByRole("button", { name: /adicionar banana prata/i }));
    await user.click(screen.getByRole("button", { name: /abrir checkout/i }));
    expect(screen.getByText("Checkout")).toBeInTheDocument();
    expect(screen.getByText("Banana prata")).toBeInTheDocument();
    expect(screen.queryByText("Entrega")).not.toBeInTheDocument();
    expect(screen.queryByText("Retirada")).not.toBeInTheDocument();
    expect(screen.queryByText("Endereco")).not.toBeInTheDocument();

    await user.click(screen.getByRole("button", { name: /gerar pix no telegram/i }));

    await waitFor(() => {
      expect(screen.getByText("Pedido Pix criado")).toBeInTheDocument();
    });
    expect(screen.getByText("MJ-TESTE-1")).toBeInTheDocument();
    expect(screen.getByText(/envie o comprovante/i)).toBeInTheDocument();

    const checkoutCall = fetchMock.mock.calls.find(([input]) =>
      String(input).includes("/api/miniapp/checkout/create"),
    );
    expect(checkoutCall).toBeDefined();
    if (!checkoutCall) throw new Error("Chamada de checkout nao encontrada.");
    const requestInit = (checkoutCall as unknown as [RequestInfo | URL, RequestInit])[1];
    const body = JSON.parse(String(requestInit?.body));
    expect(body).toMatchObject({
      forma_pagamento: "pix",
      modalidade_entrega: "retirada",
      items: [{ produto_id: "banana-prata", quantidade: 1 }],
    });
    expect(body).not.toHaveProperty("fulfillment");
    expect(body).not.toHaveProperty("address");
    expect(body).not.toHaveProperty("note");
  });
});
